// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: def.proto
// Protobuf Java Version: 4.33.2

package cls.cn.base.proto;

@com.google.protobuf.Generated
public interface BackpackPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.BackpackPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  int getCurrencyCount();
  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  boolean containsCurrency(
      int key);
  /**
   * Use {@link #getCurrencyMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Long>
  getCurrency();
  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Long>
  getCurrencyMap();
  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  long getCurrencyOrDefault(
      int key,
      long defaultValue);
  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  long getCurrencyOrThrow(
      int key);

  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  boolean containsItems(
      int key);
  /**
   * Use {@link #getItemsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb>
  getItems();
  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb>
  getItemsMap();
  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  /* nullable */
cls.cn.base.proto.ItemPb getItemsOrDefault(
      int key,
      /* nullable */
cls.cn.base.proto.ItemPb defaultValue);
  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  cls.cn.base.proto.ItemPb getItemsOrThrow(
      int key);
}
