// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: def.proto
// Protobuf Java Version: 4.33.2

package cls.cn.base.proto;

/**
 * <pre>
 * 背包
 * </pre>
 *
 * Protobuf type {@code protobuf.BackpackPb}
 */
@com.google.protobuf.Generated
public final class BackpackPb extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protobuf.BackpackPb)
    BackpackPbOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "BackpackPb");
  }
  // Use BackpackPb.newBuilder() to construct.
  private BackpackPb(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BackpackPb() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cls.cn.base.proto.Def.internal_static_protobuf_BackpackPb_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetCurrency();
      case 2:
        return internalGetItems();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cls.cn.base.proto.Def.internal_static_protobuf_BackpackPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cls.cn.base.proto.BackpackPb.class, cls.cn.base.proto.BackpackPb.Builder.class);
  }

  public static final int CURRENCY_FIELD_NUMBER = 1;
  private static final class CurrencyDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Long>newDefaultInstance(
                cls.cn.base.proto.Def.internal_static_protobuf_BackpackPb_CurrencyEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Long> currency_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
  internalGetCurrency() {
    if (currency_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CurrencyDefaultEntryHolder.defaultEntry);
    }
    return currency_;
  }
  public int getCurrencyCount() {
    return internalGetCurrency().getMap().size();
  }
  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  @java.lang.Override
  public boolean containsCurrency(
      int key) {

    return internalGetCurrency().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCurrencyMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Long> getCurrency() {
    return getCurrencyMap();
  }
  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Integer, java.lang.Long> getCurrencyMap() {
    return internalGetCurrency().getMap();
  }
  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  @java.lang.Override
  public long getCurrencyOrDefault(
      int key,
      long defaultValue) {

    java.util.Map<java.lang.Integer, java.lang.Long> map =
        internalGetCurrency().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 货币
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; currency = 1;</code>
   */
  @java.lang.Override
  public long getCurrencyOrThrow(
      int key) {

    java.util.Map<java.lang.Integer, java.lang.Long> map =
        internalGetCurrency().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ITEMS_FIELD_NUMBER = 2;
  private static final class ItemsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, cls.cn.base.proto.ItemPb> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, cls.cn.base.proto.ItemPb>newDefaultInstance(
                cls.cn.base.proto.Def.internal_static_protobuf_BackpackPb_ItemsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                cls.cn.base.proto.ItemPb.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Integer, cls.cn.base.proto.ItemPb> items_;
  private com.google.protobuf.MapField<java.lang.Integer, cls.cn.base.proto.ItemPb>
  internalGetItems() {
    if (items_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ItemsDefaultEntryHolder.defaultEntry);
    }
    return items_;
  }
  public int getItemsCount() {
    return internalGetItems().getMap().size();
  }
  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  @java.lang.Override
  public boolean containsItems(
      int key) {

    return internalGetItems().getMap().containsKey(key);
  }
  /**
   * Use {@link #getItemsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb> getItems() {
    return getItemsMap();
  }
  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb> getItemsMap() {
    return internalGetItems().getMap();
  }
  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  @java.lang.Override
  public /* nullable */
cls.cn.base.proto.ItemPb getItemsOrDefault(
      int key,
      /* nullable */
cls.cn.base.proto.ItemPb defaultValue) {

    java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb> map =
        internalGetItems().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 道具
   * </pre>
   *
   * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
   */
  @java.lang.Override
  public cls.cn.base.proto.ItemPb getItemsOrThrow(
      int key) {

    java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb> map =
        internalGetItems().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeIntegerMapTo(
        output,
        internalGetCurrency(),
        CurrencyDefaultEntryHolder.defaultEntry,
        1);
    com.google.protobuf.GeneratedMessage
      .serializeIntegerMapTo(
        output,
        internalGetItems(),
        ItemsDefaultEntryHolder.defaultEntry,
        2);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Long> entry
         : internalGetCurrency().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
      currency__ = CurrencyDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, currency__);
    }
    for (java.util.Map.Entry<java.lang.Integer, cls.cn.base.proto.ItemPb> entry
         : internalGetItems().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, cls.cn.base.proto.ItemPb>
      items__ = ItemsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cls.cn.base.proto.BackpackPb)) {
      return super.equals(obj);
    }
    cls.cn.base.proto.BackpackPb other = (cls.cn.base.proto.BackpackPb) obj;

    if (!internalGetCurrency().equals(
        other.internalGetCurrency())) return false;
    if (!internalGetItems().equals(
        other.internalGetItems())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetCurrency().getMap().isEmpty()) {
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCurrency().hashCode();
    }
    if (!internalGetItems().getMap().isEmpty()) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetItems().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cls.cn.base.proto.BackpackPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cls.cn.base.proto.BackpackPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cls.cn.base.proto.BackpackPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cls.cn.base.proto.BackpackPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cls.cn.base.proto.BackpackPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 背包
   * </pre>
   *
   * Protobuf type {@code protobuf.BackpackPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.BackpackPb)
      cls.cn.base.proto.BackpackPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cls.cn.base.proto.Def.internal_static_protobuf_BackpackPb_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetCurrency();
        case 2:
          return internalGetItems();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableCurrency();
        case 2:
          return internalGetMutableItems();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cls.cn.base.proto.Def.internal_static_protobuf_BackpackPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cls.cn.base.proto.BackpackPb.class, cls.cn.base.proto.BackpackPb.Builder.class);
    }

    // Construct using cls.cn.base.proto.BackpackPb.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableCurrency().clear();
      internalGetMutableItems().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cls.cn.base.proto.Def.internal_static_protobuf_BackpackPb_descriptor;
    }

    @java.lang.Override
    public cls.cn.base.proto.BackpackPb getDefaultInstanceForType() {
      return cls.cn.base.proto.BackpackPb.getDefaultInstance();
    }

    @java.lang.Override
    public cls.cn.base.proto.BackpackPb build() {
      cls.cn.base.proto.BackpackPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cls.cn.base.proto.BackpackPb buildPartial() {
      cls.cn.base.proto.BackpackPb result = new cls.cn.base.proto.BackpackPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cls.cn.base.proto.BackpackPb result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.currency_ = internalGetCurrency();
        result.currency_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.items_ = internalGetItems().build(ItemsDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cls.cn.base.proto.BackpackPb) {
        return mergeFrom((cls.cn.base.proto.BackpackPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cls.cn.base.proto.BackpackPb other) {
      if (other == cls.cn.base.proto.BackpackPb.getDefaultInstance()) return this;
      internalGetMutableCurrency().mergeFrom(
          other.internalGetCurrency());
      bitField0_ |= 0x00000001;
      internalGetMutableItems().mergeFrom(
          other.internalGetItems());
      bitField0_ |= 0x00000002;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
              currency__ = input.readMessage(
                  CurrencyDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableCurrency().getMutableMap().put(
                  currency__.getKey(), currency__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.Integer, cls.cn.base.proto.ItemPb>
              items__ = input.readMessage(
                  ItemsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableItems().ensureBuilderMap().put(
                  items__.getKey(), items__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Long> currency_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
        internalGetCurrency() {
      if (currency_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CurrencyDefaultEntryHolder.defaultEntry);
      }
      return currency_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
        internalGetMutableCurrency() {
      if (currency_ == null) {
        currency_ = com.google.protobuf.MapField.newMapField(
            CurrencyDefaultEntryHolder.defaultEntry);
      }
      if (!currency_.isMutable()) {
        currency_ = currency_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return currency_;
    }
    public int getCurrencyCount() {
      return internalGetCurrency().getMap().size();
    }
    /**
     * <pre>
     * 货币
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; currency = 1;</code>
     */
    @java.lang.Override
    public boolean containsCurrency(
        int key) {

      return internalGetCurrency().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCurrencyMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long> getCurrency() {
      return getCurrencyMap();
    }
    /**
     * <pre>
     * 货币
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; currency = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, java.lang.Long> getCurrencyMap() {
      return internalGetCurrency().getMap();
    }
    /**
     * <pre>
     * 货币
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; currency = 1;</code>
     */
    @java.lang.Override
    public long getCurrencyOrDefault(
        int key,
        long defaultValue) {

      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetCurrency().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 货币
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; currency = 1;</code>
     */
    @java.lang.Override
    public long getCurrencyOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetCurrency().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearCurrency() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableCurrency().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 货币
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; currency = 1;</code>
     */
    public Builder removeCurrency(
        int key) {

      internalGetMutableCurrency().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long>
        getMutableCurrency() {
      bitField0_ |= 0x00000001;
      return internalGetMutableCurrency().getMutableMap();
    }
    /**
     * <pre>
     * 货币
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; currency = 1;</code>
     */
    public Builder putCurrency(
        int key,
        long value) {


      internalGetMutableCurrency().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * 货币
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; currency = 1;</code>
     */
    public Builder putAllCurrency(
        java.util.Map<java.lang.Integer, java.lang.Long> values) {
      internalGetMutableCurrency().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }

    private static final class ItemsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.Integer, cls.cn.base.proto.ItemPbOrBuilder, cls.cn.base.proto.ItemPb> {
      @java.lang.Override
      public cls.cn.base.proto.ItemPb build(cls.cn.base.proto.ItemPbOrBuilder val) {
        if (val instanceof cls.cn.base.proto.ItemPb) { return (cls.cn.base.proto.ItemPb) val; }
        return ((cls.cn.base.proto.ItemPb.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.Integer, cls.cn.base.proto.ItemPb> defaultEntry() {
        return ItemsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ItemsConverter itemsConverter = new ItemsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.Integer, cls.cn.base.proto.ItemPbOrBuilder, cls.cn.base.proto.ItemPb, cls.cn.base.proto.ItemPb.Builder> items_;
    private com.google.protobuf.MapFieldBuilder<java.lang.Integer, cls.cn.base.proto.ItemPbOrBuilder, cls.cn.base.proto.ItemPb, cls.cn.base.proto.ItemPb.Builder>
        internalGetItems() {
      if (items_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(itemsConverter);
      }
      return items_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.Integer, cls.cn.base.proto.ItemPbOrBuilder, cls.cn.base.proto.ItemPb, cls.cn.base.proto.ItemPb.Builder>
        internalGetMutableItems() {
      if (items_ == null) {
        items_ = new com.google.protobuf.MapFieldBuilder<>(itemsConverter);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return items_;
    }
    public int getItemsCount() {
      return internalGetItems().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * 道具
     * </pre>
     *
     * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
     */
    @java.lang.Override
    public boolean containsItems(
        int key) {

      return internalGetItems().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getItemsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb> getItems() {
      return getItemsMap();
    }
    /**
     * <pre>
     * 道具
     * </pre>
     *
     * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb> getItemsMap() {
      return internalGetItems().getImmutableMap();
    }
    /**
     * <pre>
     * 道具
     * </pre>
     *
     * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
cls.cn.base.proto.ItemPb getItemsOrDefault(
        int key,
        /* nullable */
cls.cn.base.proto.ItemPb defaultValue) {

      java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPbOrBuilder> map = internalGetMutableItems().ensureBuilderMap();
      return map.containsKey(key) ? itemsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * 道具
     * </pre>
     *
     * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
     */
    @java.lang.Override
    public cls.cn.base.proto.ItemPb getItemsOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPbOrBuilder> map = internalGetMutableItems().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return itemsConverter.build(map.get(key));
    }
    public Builder clearItems() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableItems().clear();
      return this;
    }
    /**
     * <pre>
     * 道具
     * </pre>
     *
     * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
     */
    public Builder removeItems(
        int key) {

      internalGetMutableItems().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb>
        getMutableItems() {
      bitField0_ |= 0x00000002;
      return internalGetMutableItems().ensureMessageMap();
    }
    /**
     * <pre>
     * 道具
     * </pre>
     *
     * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
     */
    public Builder putItems(
        int key,
        cls.cn.base.proto.ItemPb value) {

      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableItems().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * 道具
     * </pre>
     *
     * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
     */
    public Builder putAllItems(
        java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPb> values) {
      for (java.util.Map.Entry<java.lang.Integer, cls.cn.base.proto.ItemPb> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableItems().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * 道具
     * </pre>
     *
     * <code>map&lt;int32, .protobuf.ItemPb&gt; items = 2;</code>
     */
    public cls.cn.base.proto.ItemPb.Builder putItemsBuilderIfAbsent(
        int key) {
      java.util.Map<java.lang.Integer, cls.cn.base.proto.ItemPbOrBuilder> builderMap = internalGetMutableItems().ensureBuilderMap();
      cls.cn.base.proto.ItemPbOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = cls.cn.base.proto.ItemPb.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof cls.cn.base.proto.ItemPb) {
        entry = ((cls.cn.base.proto.ItemPb) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (cls.cn.base.proto.ItemPb.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:protobuf.BackpackPb)
  }

  // @@protoc_insertion_point(class_scope:protobuf.BackpackPb)
  private static final cls.cn.base.proto.BackpackPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cls.cn.base.proto.BackpackPb();
  }

  public static cls.cn.base.proto.BackpackPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BackpackPb>
      PARSER = new com.google.protobuf.AbstractParser<BackpackPb>() {
    @java.lang.Override
    public BackpackPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BackpackPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BackpackPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cls.cn.base.proto.BackpackPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

