// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: def.proto
// Protobuf Java Version: 4.33.2

package cls.cn.base.proto;

@com.google.protobuf.Generated
public final class Def extends com.google.protobuf.GeneratedFile {
  private Def() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "Def");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(cls.cn.base.proto.Def.msgId);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int MSGID_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Integer> msgId = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_PlayerPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_PlayerPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_LevelPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_LevelPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_BackpackPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_BackpackPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_BackpackPb_CurrencyEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_BackpackPb_CurrencyEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_BackpackPb_ItemsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_BackpackPb_ItemsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ItemPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_ItemPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tdef.proto\022\010protobuf\032(include/google/pr" +
      "otobuf/descriptor.proto\"\235\001\n\010PlayerPb\022\n\n\002" +
      "id\030\001 \001(\t\022\021\n\004name\030\002 \001(\tH\000\210\001\001\022%\n\005level\030\003 \001" +
      "(\0132\021.protobuf.LevelPbH\001\210\001\001\022+\n\010backpack\030\004" +
      " \001(\0132\024.protobuf.BackpackPbH\002\210\001\001B\007\n\005_name" +
      "B\010\n\006_levelB\013\n\t_backpack\"A\n\007LevelPb\022\022\n\005le" +
      "vel\030\001 \001(\005H\000\210\001\001\022\020\n\003exp\030\002 \001(\003H\001\210\001\001B\010\n\006_lev" +
      "elB\006\n\004_exp\"\343\001\n\nBackpackPb\0224\n\010currency\030\001 " +
      "\003(\0132\".protobuf.BackpackPb.CurrencyEntry\022" +
      ".\n\005items\030\002 \003(\0132\037.protobuf.BackpackPb.Ite" +
      "msEntry\032/\n\rCurrencyEntry\022\013\n\003key\030\001 \001(\005\022\r\n" +
      "\005value\030\002 \001(\003:\0028\001\032>\n\nItemsEntry\022\013\n\003key\030\001 " +
      "\001(\005\022\037\n\005value\030\002 \001(\0132\020.protobuf.ItemPb:\0028\001" +
      "\">\n\006ItemPb\022\017\n\002id\030\001 \001(\005H\000\210\001\001\022\022\n\005count\030\002 \001" +
      "(\003H\001\210\001\001B\005\n\003_idB\010\n\006_count:3\n\005msgId\022\037.goog" +
      "le.protobuf.MessageOptions\030\320\206\003 \001(\005\210\001\001B\025\n" +
      "\021cls.cn.base.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_protobuf_PlayerPb_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_protobuf_PlayerPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_PlayerPb_descriptor,
        new java.lang.String[] { "Id", "Name", "Level", "Backpack", });
    internal_static_protobuf_LevelPb_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_protobuf_LevelPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_LevelPb_descriptor,
        new java.lang.String[] { "Level", "Exp", });
    internal_static_protobuf_BackpackPb_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_protobuf_BackpackPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_BackpackPb_descriptor,
        new java.lang.String[] { "Currency", "Items", });
    internal_static_protobuf_BackpackPb_CurrencyEntry_descriptor =
      internal_static_protobuf_BackpackPb_descriptor.getNestedType(0);
    internal_static_protobuf_BackpackPb_CurrencyEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_BackpackPb_CurrencyEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protobuf_BackpackPb_ItemsEntry_descriptor =
      internal_static_protobuf_BackpackPb_descriptor.getNestedType(1);
    internal_static_protobuf_BackpackPb_ItemsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_BackpackPb_ItemsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protobuf_ItemPb_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_protobuf_ItemPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_ItemPb_descriptor,
        new java.lang.String[] { "Id", "Count", });
    msgId.internalInit(descriptor.getExtension(0));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
