// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: def.proto
// Protobuf Java Version: 4.33.2

package cls.cn.base.proto;

@com.google.protobuf.Generated
public interface ItemPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.ItemPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * id
   * </pre>
   *
   * <code>optional int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * id
   * </pre>
   *
   * <code>optional int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   * 数量
   * </pre>
   *
   * <code>optional int64 count = 2;</code>
   * @return Whether the count field is set.
   */
  boolean hasCount();
  /**
   * <pre>
   * 数量
   * </pre>
   *
   * <code>optional int64 count = 2;</code>
   * @return The count.
   */
  long getCount();
}
