// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: def.proto
// Protobuf Java Version: 4.33.2

package cls.cn.base.proto;

@com.google.protobuf.Generated
public interface LevelPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.LevelPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>optional int32 level = 1;</code>
   * @return Whether the level field is set.
   */
  boolean hasLevel();
  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>optional int32 level = 1;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   * 经验
   * </pre>
   *
   * <code>optional int64 exp = 2;</code>
   * @return Whether the exp field is set.
   */
  boolean hasExp();
  /**
   * <pre>
   * 经验
   * </pre>
   *
   * <code>optional int64 exp = 2;</code>
   * @return The exp.
   */
  long getExp();
}
