// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: def.proto
// Protobuf Java Version: 4.33.2

package cls.cn.base.proto;

@com.google.protobuf.Generated
public interface PlayerPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.PlayerPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 玩家id
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * 玩家id
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>optional .protobuf.LevelPb level = 3;</code>
   * @return Whether the level field is set.
   */
  boolean hasLevel();
  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>optional .protobuf.LevelPb level = 3;</code>
   * @return The level.
   */
  cls.cn.base.proto.LevelPb getLevel();
  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>optional .protobuf.LevelPb level = 3;</code>
   */
  cls.cn.base.proto.LevelPbOrBuilder getLevelOrBuilder();

  /**
   * <pre>
   * 背包
   * </pre>
   *
   * <code>optional .protobuf.BackpackPb backpack = 4;</code>
   * @return Whether the backpack field is set.
   */
  boolean hasBackpack();
  /**
   * <pre>
   * 背包
   * </pre>
   *
   * <code>optional .protobuf.BackpackPb backpack = 4;</code>
   * @return The backpack.
   */
  cls.cn.base.proto.BackpackPb getBackpack();
  /**
   * <pre>
   * 背包
   * </pre>
   *
   * <code>optional .protobuf.BackpackPb backpack = 4;</code>
   */
  cls.cn.base.proto.BackpackPbOrBuilder getBackpackOrBuilder();
}
