// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: def.proto
// Protobuf Java Version: 4.33.2

package cls.cn.base.proto;

/**
 * <pre>
 * 玩家数据
 * </pre>
 *
 * Protobuf type {@code protobuf.PlayerPb}
 */
@com.google.protobuf.Generated
public final class PlayerPb extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protobuf.PlayerPb)
    PlayerPbOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PlayerPb");
  }
  // Use PlayerPb.newBuilder() to construct.
  private PlayerPb(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlayerPb() {
    id_ = "";
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cls.cn.base.proto.Def.internal_static_protobuf_PlayerPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cls.cn.base.proto.Def.internal_static_protobuf_PlayerPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cls.cn.base.proto.PlayerPb.class, cls.cn.base.proto.PlayerPb.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * 玩家id
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 玩家id
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEVEL_FIELD_NUMBER = 3;
  private cls.cn.base.proto.LevelPb level_;
  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>optional .protobuf.LevelPb level = 3;</code>
   * @return Whether the level field is set.
   */
  @java.lang.Override
  public boolean hasLevel() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>optional .protobuf.LevelPb level = 3;</code>
   * @return The level.
   */
  @java.lang.Override
  public cls.cn.base.proto.LevelPb getLevel() {
    return level_ == null ? cls.cn.base.proto.LevelPb.getDefaultInstance() : level_;
  }
  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>optional .protobuf.LevelPb level = 3;</code>
   */
  @java.lang.Override
  public cls.cn.base.proto.LevelPbOrBuilder getLevelOrBuilder() {
    return level_ == null ? cls.cn.base.proto.LevelPb.getDefaultInstance() : level_;
  }

  public static final int BACKPACK_FIELD_NUMBER = 4;
  private cls.cn.base.proto.BackpackPb backpack_;
  /**
   * <pre>
   * 背包
   * </pre>
   *
   * <code>optional .protobuf.BackpackPb backpack = 4;</code>
   * @return Whether the backpack field is set.
   */
  @java.lang.Override
  public boolean hasBackpack() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 背包
   * </pre>
   *
   * <code>optional .protobuf.BackpackPb backpack = 4;</code>
   * @return The backpack.
   */
  @java.lang.Override
  public cls.cn.base.proto.BackpackPb getBackpack() {
    return backpack_ == null ? cls.cn.base.proto.BackpackPb.getDefaultInstance() : backpack_;
  }
  /**
   * <pre>
   * 背包
   * </pre>
   *
   * <code>optional .protobuf.BackpackPb backpack = 4;</code>
   */
  @java.lang.Override
  public cls.cn.base.proto.BackpackPbOrBuilder getBackpackOrBuilder() {
    return backpack_ == null ? cls.cn.base.proto.BackpackPb.getDefaultInstance() : backpack_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getLevel());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getBackpack());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLevel());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBackpack());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cls.cn.base.proto.PlayerPb)) {
      return super.equals(obj);
    }
    cls.cn.base.proto.PlayerPb other = (cls.cn.base.proto.PlayerPb) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasLevel() != other.hasLevel()) return false;
    if (hasLevel()) {
      if (!getLevel()
          .equals(other.getLevel())) return false;
    }
    if (hasBackpack() != other.hasBackpack()) return false;
    if (hasBackpack()) {
      if (!getBackpack()
          .equals(other.getBackpack())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasLevel()) {
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel().hashCode();
    }
    if (hasBackpack()) {
      hash = (37 * hash) + BACKPACK_FIELD_NUMBER;
      hash = (53 * hash) + getBackpack().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cls.cn.base.proto.PlayerPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cls.cn.base.proto.PlayerPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cls.cn.base.proto.PlayerPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cls.cn.base.proto.PlayerPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cls.cn.base.proto.PlayerPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 玩家数据
   * </pre>
   *
   * Protobuf type {@code protobuf.PlayerPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.PlayerPb)
      cls.cn.base.proto.PlayerPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cls.cn.base.proto.Def.internal_static_protobuf_PlayerPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cls.cn.base.proto.Def.internal_static_protobuf_PlayerPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cls.cn.base.proto.PlayerPb.class, cls.cn.base.proto.PlayerPb.Builder.class);
    }

    // Construct using cls.cn.base.proto.PlayerPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetLevelFieldBuilder();
        internalGetBackpackFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = "";
      level_ = null;
      if (levelBuilder_ != null) {
        levelBuilder_.dispose();
        levelBuilder_ = null;
      }
      backpack_ = null;
      if (backpackBuilder_ != null) {
        backpackBuilder_.dispose();
        backpackBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cls.cn.base.proto.Def.internal_static_protobuf_PlayerPb_descriptor;
    }

    @java.lang.Override
    public cls.cn.base.proto.PlayerPb getDefaultInstanceForType() {
      return cls.cn.base.proto.PlayerPb.getDefaultInstance();
    }

    @java.lang.Override
    public cls.cn.base.proto.PlayerPb build() {
      cls.cn.base.proto.PlayerPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cls.cn.base.proto.PlayerPb buildPartial() {
      cls.cn.base.proto.PlayerPb result = new cls.cn.base.proto.PlayerPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cls.cn.base.proto.PlayerPb result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.level_ = levelBuilder_ == null
            ? level_
            : levelBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.backpack_ = backpackBuilder_ == null
            ? backpack_
            : backpackBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cls.cn.base.proto.PlayerPb) {
        return mergeFrom((cls.cn.base.proto.PlayerPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cls.cn.base.proto.PlayerPb other) {
      if (other == cls.cn.base.proto.PlayerPb.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasName()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasLevel()) {
        mergeLevel(other.getLevel());
      }
      if (other.hasBackpack()) {
        mergeBackpack(other.getBackpack());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetLevelFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetBackpackFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private cls.cn.base.proto.LevelPb level_;
    private com.google.protobuf.SingleFieldBuilder<
        cls.cn.base.proto.LevelPb, cls.cn.base.proto.LevelPb.Builder, cls.cn.base.proto.LevelPbOrBuilder> levelBuilder_;
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     * @return Whether the level field is set.
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     * @return The level.
     */
    public cls.cn.base.proto.LevelPb getLevel() {
      if (levelBuilder_ == null) {
        return level_ == null ? cls.cn.base.proto.LevelPb.getDefaultInstance() : level_;
      } else {
        return levelBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     */
    public Builder setLevel(cls.cn.base.proto.LevelPb value) {
      if (levelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        level_ = value;
      } else {
        levelBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     */
    public Builder setLevel(
        cls.cn.base.proto.LevelPb.Builder builderForValue) {
      if (levelBuilder_ == null) {
        level_ = builderForValue.build();
      } else {
        levelBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     */
    public Builder mergeLevel(cls.cn.base.proto.LevelPb value) {
      if (levelBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          level_ != null &&
          level_ != cls.cn.base.proto.LevelPb.getDefaultInstance()) {
          getLevelBuilder().mergeFrom(value);
        } else {
          level_ = value;
        }
      } else {
        levelBuilder_.mergeFrom(value);
      }
      if (level_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     */
    public Builder clearLevel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      level_ = null;
      if (levelBuilder_ != null) {
        levelBuilder_.dispose();
        levelBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     */
    public cls.cn.base.proto.LevelPb.Builder getLevelBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetLevelFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     */
    public cls.cn.base.proto.LevelPbOrBuilder getLevelOrBuilder() {
      if (levelBuilder_ != null) {
        return levelBuilder_.getMessageOrBuilder();
      } else {
        return level_ == null ?
            cls.cn.base.proto.LevelPb.getDefaultInstance() : level_;
      }
    }
    /**
     * <pre>
     * 等级
     * </pre>
     *
     * <code>optional .protobuf.LevelPb level = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cls.cn.base.proto.LevelPb, cls.cn.base.proto.LevelPb.Builder, cls.cn.base.proto.LevelPbOrBuilder> 
        internalGetLevelFieldBuilder() {
      if (levelBuilder_ == null) {
        levelBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cls.cn.base.proto.LevelPb, cls.cn.base.proto.LevelPb.Builder, cls.cn.base.proto.LevelPbOrBuilder>(
                getLevel(),
                getParentForChildren(),
                isClean());
        level_ = null;
      }
      return levelBuilder_;
    }

    private cls.cn.base.proto.BackpackPb backpack_;
    private com.google.protobuf.SingleFieldBuilder<
        cls.cn.base.proto.BackpackPb, cls.cn.base.proto.BackpackPb.Builder, cls.cn.base.proto.BackpackPbOrBuilder> backpackBuilder_;
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     * @return Whether the backpack field is set.
     */
    public boolean hasBackpack() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     * @return The backpack.
     */
    public cls.cn.base.proto.BackpackPb getBackpack() {
      if (backpackBuilder_ == null) {
        return backpack_ == null ? cls.cn.base.proto.BackpackPb.getDefaultInstance() : backpack_;
      } else {
        return backpackBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     */
    public Builder setBackpack(cls.cn.base.proto.BackpackPb value) {
      if (backpackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        backpack_ = value;
      } else {
        backpackBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     */
    public Builder setBackpack(
        cls.cn.base.proto.BackpackPb.Builder builderForValue) {
      if (backpackBuilder_ == null) {
        backpack_ = builderForValue.build();
      } else {
        backpackBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     */
    public Builder mergeBackpack(cls.cn.base.proto.BackpackPb value) {
      if (backpackBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          backpack_ != null &&
          backpack_ != cls.cn.base.proto.BackpackPb.getDefaultInstance()) {
          getBackpackBuilder().mergeFrom(value);
        } else {
          backpack_ = value;
        }
      } else {
        backpackBuilder_.mergeFrom(value);
      }
      if (backpack_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     */
    public Builder clearBackpack() {
      bitField0_ = (bitField0_ & ~0x00000008);
      backpack_ = null;
      if (backpackBuilder_ != null) {
        backpackBuilder_.dispose();
        backpackBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     */
    public cls.cn.base.proto.BackpackPb.Builder getBackpackBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetBackpackFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     */
    public cls.cn.base.proto.BackpackPbOrBuilder getBackpackOrBuilder() {
      if (backpackBuilder_ != null) {
        return backpackBuilder_.getMessageOrBuilder();
      } else {
        return backpack_ == null ?
            cls.cn.base.proto.BackpackPb.getDefaultInstance() : backpack_;
      }
    }
    /**
     * <pre>
     * 背包
     * </pre>
     *
     * <code>optional .protobuf.BackpackPb backpack = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cls.cn.base.proto.BackpackPb, cls.cn.base.proto.BackpackPb.Builder, cls.cn.base.proto.BackpackPbOrBuilder> 
        internalGetBackpackFieldBuilder() {
      if (backpackBuilder_ == null) {
        backpackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cls.cn.base.proto.BackpackPb, cls.cn.base.proto.BackpackPb.Builder, cls.cn.base.proto.BackpackPbOrBuilder>(
                getBackpack(),
                getParentForChildren(),
                isClean());
        backpack_ = null;
      }
      return backpackBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:protobuf.PlayerPb)
  }

  // @@protoc_insertion_point(class_scope:protobuf.PlayerPb)
  private static final cls.cn.base.proto.PlayerPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cls.cn.base.proto.PlayerPb();
  }

  public static cls.cn.base.proto.PlayerPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerPb>
      PARSER = new com.google.protobuf.AbstractParser<PlayerPb>() {
    @java.lang.Override
    public PlayerPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cls.cn.base.proto.PlayerPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

