
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cls.cn.base.meta;

/**
 * 条件类型
 */
public final class ConditionType {
    /**
     * 玩家等级
     */
    public static final int playerLv = 101;
}

