
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cls.cn.base.meta;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import lombok.ToString;


/**
 * 条件
 */
@ToString
public final class ConditionMeta  {
    public ConditionMeta(JsonObject _buf) { 
        type = _buf.get("type").getAsInt();
        param = _buf.get("param").getAsString();
    }

    public static ConditionMeta deserialize(JsonObject _buf) {
            return new cls.cn.base.meta.ConditionMeta(_buf);
    }

    /**
     * 条件类型
     */
    public final int type;
    /**
     * 参数
     */
    public final String param;
}

