
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cls.cn.base.meta;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import lombok.ToString;


/**
 * 奖励
 */
@ToString
public final class RewardMeta  {
    public RewardMeta(JsonObject _buf) { 
        type = _buf.get("type").getAsInt();
        id = _buf.get("id").getAsInt();
        count = _buf.get("count").getAsInt();
    }

    public static RewardMeta deserialize(JsonObject _buf) {
            return new cls.cn.base.meta.RewardMeta(_buf);
    }

    /**
     * 奖励类型
     */
    public final int type;
    /**
     * 奖励id
     */
    public final int id;
    /**
     * 数量
     */
    public final int count;
}

