
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cls.cn.base.meta;

import com.google.gson.JsonElement;

public final class Tables
{

    public  interface  IJsonLoader {
        JsonElement load(String file) throws java.io.IOException;
    }

    private final cls.cn.base.meta.demo.Tbitem _tbitem;
    public cls.cn.base.meta.demo.Tbitem getTbitem() { return _tbitem; }

    public Tables(IJsonLoader loader) throws java.io.IOException {
        _tbitem = new cls.cn.base.meta.demo.Tbitem(loader.load("demo_tbitem")); 
    }
}

