
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cls.cn.base.meta.demo;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import lombok.ToString;


@ToString
public final class item  {
    public item(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        count = _buf.get("count").getAsInt();
    }

    public static item deserialize(JsonObject _buf) {
            return new cls.cn.base.meta.demo.item(_buf);
    }

    /**
     * id
     */
    public final int id;
    /**
     * 名称
     */
    public final String name;
    /**
     * 个数
     */
    public final int count;
}

